### PR TITLE
Update diffmah packaging to pyproject.toml

### PR DESCRIPTION
**Pull request by aphearin**
- Update installation requirement to python>=3.9
- Update packaging structure to pyproject.toml
- Remove diffmah/_version.py and switch to dynamic versioning

### CODE REVIEW

**Comment by aphearin** [comment]
@beckermr I think I got this right but this is the last release I'd like to do before the first Diffsky mocks that use this repo and so I figured I'd check to see if anything jumps out you.

**Comment by aphearin** [comment]
Hmmm @beckermr looks like I made some some kind of naive copypasta mistake in [this commit](https://github.com/ArgonneCPAC/diffmah/pull/109/commits/583464b8aae0c881235a88694848a434c5fd536c).

**Comment by beckermr** [comment]
Hmmmmm I'll need to debug locally to figure this out.

**Comment by beckermr** [comment]
OK @aphearin fixed - needed some deps that were missing

**Comment by aphearin** [comment]
Great - thanks for the help @beckermr!

**Pull request merged**
